# Generated by Django 5.2.4 on 2025-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorter',
            name='original_url',
            field=models.URLField(unique=True),
        ),
    ]
